/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizerRouteImport } from './routes/visualizer'
import { Route as SamplesRouteImport } from './routes/samples'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as DesignServicesRouteImport } from './routes/design-services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsFamilyIndexRouteImport } from './routes/products.$family.index'
import { Route as ProductsFamilySlugRouteImport } from './routes/products.$family.$slug'

const VisualizerRoute = VisualizerRouteImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesRoute = SamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignServicesRoute = DesignServicesRouteImport.update({
  id: '/design-services',
  path: '/design-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFamilyIndexRoute = ProductsFamilyIndexRouteImport.update({
  id: '/products/$family/',
  path: '/products/$family/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFamilySlugRoute = ProductsFamilySlugRouteImport.update({
  id: '/products/$family/$slug',
  path: '/products/$family/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/design-services': typeof DesignServicesRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/samples': typeof SamplesRoute
  '/visualizer': typeof VisualizerRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$family/$slug': typeof ProductsFamilySlugRoute
  '/products/$family/': typeof ProductsFamilyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/design-services': typeof DesignServicesRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/samples': typeof SamplesRoute
  '/visualizer': typeof VisualizerRoute
  '/products': typeof ProductsIndexRoute
  '/products/$family/$slug': typeof ProductsFamilySlugRoute
  '/products/$family': typeof ProductsFamilyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/design-services': typeof DesignServicesRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/samples': typeof SamplesRoute
  '/visualizer': typeof VisualizerRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$family/$slug': typeof ProductsFamilySlugRoute
  '/products/$family/': typeof ProductsFamilyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/design-services'
    | '/projects'
    | '/resources'
    | '/samples'
    | '/visualizer'
    | '/products/'
    | '/products/$family/$slug'
    | '/products/$family/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/design-services'
    | '/projects'
    | '/resources'
    | '/samples'
    | '/visualizer'
    | '/products'
    | '/products/$family/$slug'
    | '/products/$family'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/design-services'
    | '/projects'
    | '/resources'
    | '/samples'
    | '/visualizer'
    | '/products/'
    | '/products/$family/$slug'
    | '/products/$family/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DesignServicesRoute: typeof DesignServicesRoute
  ProjectsRoute: typeof ProjectsRoute
  ResourcesRoute: typeof ResourcesRoute
  SamplesRoute: typeof SamplesRoute
  VisualizerRoute: typeof VisualizerRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsFamilySlugRoute: typeof ProductsFamilySlugRoute
  ProductsFamilyIndexRoute: typeof ProductsFamilyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualizer': {
      id: '/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof VisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples': {
      id: '/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof SamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-services': {
      id: '/design-services'
      path: '/design-services'
      fullPath: '/design-services'
      preLoaderRoute: typeof DesignServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$family/': {
      id: '/products/$family/'
      path: '/products/$family'
      fullPath: '/products/$family/'
      preLoaderRoute: typeof ProductsFamilyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$family/$slug': {
      id: '/products/$family/$slug'
      path: '/products/$family/$slug'
      fullPath: '/products/$family/$slug'
      preLoaderRoute: typeof ProductsFamilySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DesignServicesRoute: DesignServicesRoute,
  ProjectsRoute: ProjectsRoute,
  ResourcesRoute: ResourcesRoute,
  SamplesRoute: SamplesRoute,
  VisualizerRoute: VisualizerRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsFamilySlugRoute: ProductsFamilySlugRoute,
  ProductsFamilyIndexRoute: ProductsFamilyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
